const translations = {
    en: {
      features: "Features",
      pricing: "Pricing",
      about: "About Us",
      contact: "Contact Us",
      heroTitle: "<span class='highlight-bransch'>Construction</span> industry's future is here",
      heroSubtitle: "Sign up now to get early access to the platform before launch. Enjoy exclusive features and discounted services during our limited intro period.",
      heroCTA: "Sign Up Now",
      newsletterHeading: "Be the first to try the future of construction!",
      newsletterSub: "Subscribe to our newsletter for exclusive updates, launch dates, and early platform access.",
      featureTitle: "Features that drive your success",
      featureIntro: "Discover powerful tools that simplify your construction process – from finding the right suppliers to legal advice and AI-driven support.",
      feature1Title: "Find New Suppliers & Contractors",
      feature1Desc: "Connect with reliable suppliers and contractors directly on the platform. Access a wide network of qualified partners for your next project.",
      feature2Title: "Effective Conflict Resolution",
      feature2Desc: "Quickly and smoothly resolve disputes with our built-in conflict resolution feature. We help keep your projects on track.",
      feature3Title: "Communication Directly in the Platform",
      feature3Desc: "Chat and collaborate in real-time with your team and partners. Avoid email chaos and keep everyone updated in one place.",
      feature4Title: "E-signatures and Document Management",
      feature4Desc: "Sign contracts and manage documents digitally – quickly, securely, and legally binding, directly on the platform.",
      feature5Title: "AI Chat",
      feature5Desc: "Get quick answers and insights with our AI-powered assistant. From legal questions to project planning – the AI is here to help you.",
      feature6Title: "Built-in Project Tool",
      feature6Desc: "Plan, manage, and monitor your construction projects all in one place. Streamline workflows and gain full visibility.",
      feature7Title: "Legal Advice",
      feature7Desc: "Get expert support on contracts, laws, and regulations directly on the platform. Protect your business and avoid legal pitfalls.",
      footerNewsletterTitle: "Join Our Pre-Launch Community",
      footerNewsletterDesc: "Be among the first to experience the future of construction procurement. Sign up for exclusive early access and launch updates.",
      footerNewsletterButton: "Join Now",
      footerHighlightLaunch: "Coming Soon",
      footerHighlightLaunchDesc: "We're launching soon with features that will transform how you manage construction projects",
      footerHighlightEarly: "Early Access",
      footerHighlightEarlyDesc: "Join now to get exclusive benefits and special pricing when we launch",
      footerHighlightBeta: "Beta Program",
      footerHighlightBetaDesc: "Help shape the future of our platform by joining our beta testing program",
      footerHighlightSecurity: "Data Security",
      footerHighlightSecurityDesc: "Built with enterprise-grade security and data protection from day one",
      footerHighlightSupport: "Dedicated Support",
      footerHighlightSupportDesc: "Our team is here to help you succeed with personalized assistance",
      footerHighlightQuality: "Quality First",
      footerHighlightQualityDesc: "Committed to delivering the highest quality platform for construction",
      footerCompanyTitle: "About Construction Sourcing",
      footerCompanyDesc: "We are a Swedish startup revolutionizing the construction industry through smart digitalization. Our platform will make procurement and project management more efficient and transparent.",
      footerResourcesTitle: "Resources",
      footerBlog: "Blog & News",
      footerGuides: "Guides & Tutorials",
      footerWebinars: "Webinars",
      footerSupport: "Support Center",
      footerContact: "Contact Us",
      footerEmail: "oe@constructionsourcing.se",
      footerPhone: "+46 73 435 35 88",
      footerStreet: "Vittangigatan 10, 162 61",
      footerCity: "Vällingby Sweden",
      footerOfficeHoursTitle: "Office Hours",
      footerOfficeHours: "Mon-Fri: 9:00 - 17:00 CET",
      footerEmergencySupport: "24/7 Emergency Support",
      footerPrivacy: "Privacy Policy",
      footerTerms: "Terms of Service",
      footerCookies: "Cookie Policy",
      footerSitemap: "Sitemap",
      footerCompany: "© 2024 Construction Sourcing Sweden AB",
      footerVersion: "Beta",
      footerBetaTag: "Pre-Launch Version coming soon",
      popupTitle: "Get regular updates about our platform",
      popupEmailPlaceholder: "Email",
      popupPhonePlaceholder: "+46",
      popupSubmit: "Sign Up",
      popupDecline: "No, Thanks",
      popupDisclaimer: "You are signing up to receive regular updates via email and can unsubscribe at any time.",
      confirmationTitle: "Thank you for signing up!",
      confirmationText: "You will now receive regular updates about the platform.",
      confirmationClose: "Close",
      heroTopText: "Be the first to experience it!",
      heroHighlightText: " Sign Up Now",
      closeButton: "✕",
      countrySE: "🇸🇪 SE",
      countryDK: "🇩🇰 DK",
      countryNO: "🇳🇴 NO",
      countryFI: "🇫🇮 FI",
      countryDE: "🇩🇪 DE",
      countryFR: "🇫🇷 FR",
      countryES: "🇪🇸 ES",
      countryIT: "🇮🇹 IT",
      countryNL: "🇳🇱 NL",
      countryBE: "🇧🇪 BE",
      aboutTitleHighlight: "Construction industry's",
      aboutTitle: "future is shaped by us",
      aboutSubtitle: "Construction Sourcing Sweden AB was founded from our own experiences of the industry's lack of transparency and recurring problems with disputes, late or missing invoice payments, and unreliable actors. During the years with Swedish Construction Sales, where Oliver Ehrenberg was CEO and Anders Niclazon chairman, we helped Nordic construction companies find reliable European suppliers and suppliers establish themselves in the Nordics. We saw how fragmented processes, insufficient communication, and incomplete contact records led to costly delays, increased suspicion, and in the worst case, money laundering. It was this insight – combined with our enthusiasm for technology and trust-based collaborations – that led us to launch Construction Sourcing Sweden AB in June 2024, a fully integrated platform designed to provide full transparency, prevent disputes, and build long-term trust.",
      aboutVisionTitle: "Our Vision",
      aboutVisionText: "Our vision is to create the obvious meeting place for all construction companies and suppliers in Europe, where all communication, all contacts, and the entire supply chain are gathered in one place. By centralizing project information, contracts, certificates, financial data, and contact lists in the same platform, we make it easy to send messages, share documents, and verify new partners without unnecessary delay. With automated notifications about invoice payments and built-in due diligence checks, users can in real-time discover unreliable actors and act proactively – all to minimize risk, avoid misunderstandings, and ensure smooth collaborations across borders.",
      featuresSummaryTitle: "What can you do on Construction Sourcing?",
      featuresSummaryIntro: "Our platform streamlines every aspect of construction procurement and project management. From finding suppliers to handling contracts, we've got you covered with powerful tools and features.",
      featuresProjectTitle: "Project & Organization",
      featuresProject1: "Create and manage multiple projects",
      featuresProject2: "Set milestones and track progress",
      featuresProject3: "Invite and manage team members",
      featuresProject4: "Share documents securely",
      featuresProject5: "Track project expenses",
      featuresProjectExpanded: "Our project management tools help you stay organized and efficient. From initial planning to final delivery, keep everything on track with our comprehensive suite of features.",
      featuresConnectTitle: "Supplier Network",
      featuresConnect1: "Find verified suppliers and contractors",
      featuresConnect2: "Compare ratings and reviews",
      featuresConnect3: "Request and manage quotes",
      featuresConnect4: "Track supplier performance",
      featuresConnect5: "Build long-term relationships",
      featuresConnectExpanded: "Connect with a network of trusted suppliers and contractors. Our platform makes it easy to find the right partners for your projects and build lasting business relationships.",
      featuresLegalTitle: "Legal & Support",
      featuresLegal1: "Contract templates and e-signing",
      featuresLegal2: "Legal document review",
      featuresLegal3: "Compliance tracking",
      featuresLegal4: "Dispute resolution",
      featuresLegal5: "AI-powered legal support",
      featuresLegalExpanded: "Get expert legal support for your construction projects. From contract templates to dispute resolution, we've got you covered with comprehensive legal tools and resources.",
      pricingTitle: "Pricing plans that grow with you",
      pricingIntro: "The platform will be completely free to use. You get immediate access to core features – without having to pay anything. In the future, there will be the possibility to pay for certain additional services and extended features for those who want to save even more time and money in their company.",
      pricingFreeTitle: "Free Access",
      pricingFreePrice: "€0/month",
      pricingFree1: "Up to 3 users",
      pricingFree2: "Manage 1 organization",
      pricingFree3: "2 active projects",
      pricingFree4: "5 RFQ & PO workflows/month",
      pricingFree5: "Chat history 7 days",
      pricingFree6: "100 notifications/month",
      pricingFreeCta: "Start for Free",
      pricingStarterTitle: "Starter",
      pricingStarterPrice: "€29/month",
      pricingStarter1: "Up to 10 users",
      pricingStarter2: "Manage up to 3 organizations",
      pricingStarter3: "10 active projects",
      pricingStarter4: "20 RFQ & PO workflows/month",
      pricingStarter5: "Chat history 30 days",
      pricingStarter6: "500 notifications/month",
      pricingStarterCta: "Get Started",
      pricingPopularBadge: "Most Popular",
      pricingAiProTitle: "AI Pro",
      pricingAiProPrice: "€49/month",
      pricingAiPro1: "Unlimited AI chat",
      pricingAiPro2: "Advanced AI insights",
      pricingAiPro3: "Custom AI reports",
      pricingAiPro4: "Priority support",
      pricingAiPro5: "AI-driven summaries",
      pricingAiProCta: "Upgrade Now",
      pricingLegalProTitle: "Legal Pro",
      pricingLegalProPrice: "€79/month",
      pricingLegalPro1: "Dedicated legal advice",
      pricingLegalPro2: "Contract templates",
      pricingLegalPro3: "Conflict resolution",
      pricingLegalPro4: "Annual legal audit",
      pricingLegalPro5: "Priority legal support",
      pricingLegalProCta: "Upgrade Now",
      pricingEnterpriseTitle: "Enterprise",
      pricingEnterprisePrice: "Starting at €199/month",
      pricingEnterprise1: "Unlimited users & teams",
      pricingEnterprise2: "Unlimited projects",
      pricingEnterprise3: "Unlimited RFQ & PO workflows",
      pricingEnterprise4: "Dedicated account manager",
      pricingEnterprise5: "Custom SLA & uptime guarantee",
      pricingEnterprise6: "Custom integrations & onboarding",
      pricingEnterpriseCta: "Contact Sales",
      pricingPrelaunchNote: "Pre-launch: Pricing and packages are preliminary. Register your interest to get notified when we launch!",
      pricingComingSoon: "Coming Soon",
      pricingInterestCta: "Register Interest",
      planBas: "Bas",
      planPlus: "Plus",
      planPremium: "Premium",
      planEnterprise: "Enterprise",
      pricingFeaturePrice: "Price",
      pricingFeatureUsers: "Max users",
      pricingFeatureProjects: "Max active projects",
      pricingFeatureRFQPO: "RFQ/PO processes/month",
      pricingFeatureDocs: "Document mgmt & e-signing",
      pricingFeatureLegal: "Legal advice",
      pricingFeatureAI: "AI-based features",
      pricingFeatureChat: "Chat & communication",
      pricingFeatureNotifications: "Notifications",
      pricingFeatureSupport: "Support level",
      pricingFeatureExtras: "Extras",
      pricingBasPrice: "49 €/month",
      pricingPlusPrice: "149 €/month",
      pricingPremiumPrice: "499 €/month",
      pricingEnterprisePrice: "1499 €/month",
      pricingBasUsers: "5",
      pricingPlusUsers: "20",
      pricingPremiumUsers: "50",
      pricingEnterpriseUsers: "Unlimited",
      pricingBasProjects: "5",
      pricingPlusProjects: "20",
      pricingPremiumProjects: "50",
      pricingEnterpriseProjects: "Unlimited",
      pricingBasRFQPO: "20",
      pricingPlusRFQPO: "100",
      pricingPremiumRFQPO: "500",
      pricingEnterpriseRFQPO: "Unlimited",
      pricingBasDocs: "Basic (limited storage), up to 10 e-sign/month",
      pricingPlusDocs: "Standard (more storage), up to 50 e-sign/month",
      pricingPremiumDocs: "Advanced (large storage, versioning), up to 200 e-sign/month",
      pricingEnterpriseDocs: "Full (unlimited storage & e-sign)",
      pricingBasLegal: "Self-service (templates & guides)",
      pricingPlusLegal: "Limited (1 case/month via email)",
      pricingPremiumLegal: "Extended (5h consultation/month)",
      pricingEnterpriseLegal: "Comprehensive (dedicated legal contact)",
      pricingBasAI: "No AI features",
      pricingPlusAI: "Basic assistance",
      pricingPremiumAI: "Advanced (AI assistant & insights)",
      pricingEnterpriseAI: "Full AI suite (all features, customized)",
      pricingBasChat: "Internal chat (team only)",
      pricingPlusChat: "Team chat & project communication",
      pricingPremiumChat: "Advanced chat (group chat, external users)",
      pricingEnterpriseChat: "Full communication (incl. integrations)",
      pricingBasNotifications: "Email only",
      pricingPlusNotifications: "Email + push notifications",
      pricingPremiumNotifications: "Email, push + SMS (up to 50/month)",
      pricingEnterpriseNotifications: "Email, push + SMS (unlimited)",
      pricingBasSupport: "Email (reply within 48h, business hours)",
      pricingPlusSupport: "Email (reply within 24h) + chat",
      pricingPremiumSupport: "Priority (phone & email, business hours)",
      pricingEnterpriseSupport: "24/7 support (dedicated contact)",
      pricingBasExtras: "Self-service (online guides); no add-ons",
      pricingPlusExtras: "Onboarding webinar; no add-ons",
      pricingPremiumExtras: "Personal onboarding (expert support); SSO & API optional",
      pricingEnterpriseExtras: "Fullständig onboarding & training; SSO & API ingår",
      basDetailsTitle: "Free Plan (Bas) – Detailed Overview",
      basDetailsPrice: "<strong>Price:</strong> 0 €/month (excl. VAT)",
      basDetailsUsers: "<strong>Users:</strong> Up to 3 users",
      basDetailsOrgs: "<strong>Organizations:</strong> Manage 1 organization",
      basDetailsProjects: "<strong>Projects:</strong> Max 2 active projects at once",
      basDetailsRFQPO: "<strong>RFQ & PO workflows:</strong> Max 5 per month",
      basDetailsDocs: "<strong>Document mgmt:</strong> Limited storage (e.g. max 500 MB) and up to 10 e-signatures per month",
      basDetailsChat: "<strong>Chat:</strong> Simple team chat within the organization",
      basDetailsNotifications: "<strong>Notifications:</strong> 100 email notifications per month",
      basDetailsAI: "<strong>AI features:</strong> No AI features enabled",
      basDetailsLegal: "<strong>Legal & advice:</strong> Only access to templates and guides (no personal advice)",
      basDetailsSupport: "<strong>Support:</strong> Self-service via FAQ and documentation (no direct email or chat support)",
      basDetailsOther: "<strong>Other:</strong> Branding: Platform logo and standard settings (no customization)",
      planFree: "Free",
      pricingFreeBadge: "Always free",
      pricingFreePrice: "0 €/month",
      pricingFreeUsers: "Up to 3 users",
      pricingFreeProjects: "Max 2 active projects",
      pricingFreeRFQPO: "Max 5 per month",
      pricingFreeDocs: "Limited storage (max 500 MB), up to 10 e-sign/month",
      pricingFreeLegal: "Templates & guides only",
      pricingFreeAI: "No AI features",
      pricingFreeChat: "Team chat only",
      pricingFreeNotifications: "100 email notifications/month",
      pricingFreeSupport: "Self-service FAQ only",
      pricingFreeExtras: "Platform branding only",
      emailError: "Please enter a valid email address",
      phoneError: "Please enter a valid phone number",
      submitError: "Something went wrong. Please try again.",
      useCase1Title: "Smart Procurement",
      useCase1Desc: "Find verified suppliers, manage RFQs, and handle contracts all in one place.",
      useCase1Expanded: "Our procurement system simplifies the entire process from supplier discovery to contract signing. Get access to a verified network of construction suppliers, manage RFQs, and handle contracts efficiently.",
      useCase2Title: "Project Management",
      useCase2Desc: "Create and manage projects, track progress, and collaborate with your team.",
      useCase2Expanded: "Streamline your construction projects with our comprehensive management tools. Create projects, set milestones, track progress, and collaborate with your team in real-time.",
      useCase3Title: "Communication Hub",
      useCase3Desc: "Chat, share documents, and stay updated with real-time notifications.",
      useCase3Expanded: "Keep your team aligned with our integrated communication tools. Chat in real-time, share documents securely, and stay updated with smart notifications.",
      aboutFoundersTitle: "Meet the Visionaries Behind Construction Sourcing",
      aboutOliverRole: "CEO & Co-founder",
      aboutOliverBio: "Oliver Ehrenberg holds a Bachelor's degree in Innovation Management and is the founder of Neo Marketing, with extensive experience in CRM implementation and data-driven business models. As CEO of Swedish Construction Sales from 2021 to 2024, he led the work of connecting Nordic construction companies to European suppliers and witnessed firsthand how lack of transparency and incorrect communication caused unnecessary conflicts. This insight made him determined to develop a platform that not only handles data but also enables simple, transparent dialogue between all parties – regardless of where in Europe they operate.",
      aboutAndersRole: "CTO & Co-founder",
      aboutAndersBio: "Anders Niclazon has over two decades of experience as an entrepreneur and strategic advisor, specializing in HubSpot CRM and digital sales. As chairman of Swedish Construction Sales, he was responsible for partnerships, business development, and structured due diligence processes that significantly reduced disputes and increased trust between customers and suppliers. Together with Oliver, he founded Construction Sourcing Sweden AB to scale up this solution, centralize all contacts and communication flows, and create a secure, efficient platform where every construction company and supplier in Europe can establish themselves, grow, and collaborate successfully."
    },
    sv: {
      features: "Funktioner",
      pricing: "Prissättning",
      about: "Om oss",
      contact: "Kontakta oss",
      heroTitle: "<span class='highlight-bransch'>Byggbranschens</span> framtid är här",
      heroSubtitle: " Registrera dig nu och få chansen att testa plattformen redan innan vi lanserar. Under en begränsad introduktionsperiod får du fri tillgång till flera unika funktioner och rabatterade priser på utvalda tjänster efter lanseringen.",
      heroCTA: "Anmäl Dig Nu",
      newsletterHeading: "Bli först med att testa framtidens byggplattform!",
      newsletterSub: "Registrera dig för vårt nyhetsbrev och få exklusiv tillgång till uppdateringar, lanseringsdatum och tidig åtkomst till plattformen.",
      featureTitle: "Funktioner som driver din framgång",
      featureIntro: "Upptäck kraftfulla verktyg som förenklar din byggprocess – från att hitta rätt leverantörer till juridisk rådgivning och AI‑driven support.",
      feature1Title: "Hitta nya Leverantörer & Entreprenörer",
      feature1Desc: "Anslut med pålitliga leverantörer och entreprenörer direkt på plattformen. Få tillgång till ett brett nätverk av kvalificerade partners för ditt nästa projekt.",
      feature2Title: "Effektiv Konfliktlösning",
      feature2Desc: "Lös tvister snabbt och smidigt med vår inbyggda konfliktlösningsfunktion. Vi hjälper till att hålla dina projekt på rätt spår.",
      feature3Title: "Kommunikation Direkt i Plattformen",
      feature3Desc: "Chatta och samarbeta i realtid med ditt team och partners. Slipp e‑postkaoset och håll alla uppdaterade på ett ställe.",
      feature4Title: "E-signatur och dokumenthantering",
      feature4Desc: "Signera avtal och hantera dokument digitalt – snabbt, säkert och juridiskt bindande, direkt på plattformen.",
      feature5Title: "AI Chat",
      feature5Desc: "Få snabba svar och insikter med vår AI-drivna assistent. Från juridiska frågor till projektplanering – AI:n är här för att hjälpa dig.",
      feature6Title: "Inbyggt Projektverktyg",
      feature6Desc: "Planera, hantera och övervaka dina byggprojekt på ett och samma ställe. Effektivisera arbetsflöden och få full överblick.",
      feature7Title: "Juridisk Rådgivning",
      feature7Desc: "Få expertstöd om kontrakt, lagar och regler direkt i plattformen. Skydda ditt företag och undvik juridiska fallgropar.",
      footerNewsletterTitle: "Gå med i vår Pre-Launch Community",
      footerNewsletterDesc: "Var bland de första att uppleva framtiden inom byggupphandling. Registrera dig för exklusiv förhandsåtkomst och lanseringsuppdateringar.",
      footerNewsletterButton: "Gå med nu",
      footerHighlightLaunch: "Kommer Snart",
      footerHighlightLaunchDesc: "Vi lanserar snart med funktioner som kommer att förändra hur du hanterar byggprojekt",
      footerHighlightEarly: "Förhandsåtkomst",
      footerHighlightEarlyDesc: "Gå med nu för att få exklusiva förmåner och specialpriser när vi lanserar",
      footerHighlightBeta: "Beta-program",
      footerHighlightBetaDesc: "Hjälp till att forma framtiden för vår plattform genom att gå med i vårt betatestprogram",
      footerHighlightSecurity: "Datasäkerhet",
      footerHighlightSecurityDesc: "Byggd med företagsklass säkerhet och dataskydd från dag ett",
      footerHighlightSupport: "Dedikerad Support",
      footerHighlightSupportDesc: "Vårt team finns här för att hjälpa dig lyckas med personlig assistans",
      footerHighlightQuality: "Kvalitet Först",
      footerHighlightQualityDesc: "Dedikerade till att leverera den högsta kvalitetsplattformen för byggbranschen",
      footerCompanyTitle: "Om Construction Sourcing",
      footerCompanyDesc: "Vi är ett svenskt startup som revolutionerar byggbranschen genom smart digitalisering. Vår plattform kommer att göra upphandling och projektledning mer effektiv och transparent.",
      footerResourcesTitle: "Resurser",
      footerBlog: "Blogg & Nyheter",
      footerGuides: "Guider & Tutorials",
      footerWebinars: "Webbinarier",
      footerSupport: "Supportcenter",
      footerContact: "Kontakta Oss",
      footerEmail: "oe@constructionsourcing.se",
      footerPhone: "+46 73 435 35 88",
      footerStreet: "Vittangigatan 10, 162 61",
      footerCity: "Vällingby Sweden",
      footerOfficeHoursTitle: "Öppettider",
      footerOfficeHours: "Mån-Fre: 09:00 - 17:00 CET",
      footerEmergencySupport: "Akutsupport Dygnet Runt",
      footerPrivacy: "Integritetspolicy",
      footerTerms: "Användarvillkor",
      footerCookies: "Cookie-policy",
      footerSitemap: "Sidkarta",
      footerCompany: "© 2024 Construction Sourcing Sweden AB",
      footerVersion: "Beta",
      footerBetaTag: "Pre-Launch Version kommer snart",
      popupTitle: "Få regelbundna uppdateringar om vår plattform",
      popupEmailPlaceholder: "E‑post",
      popupPhonePlaceholder: "+46",
      popupSubmit: "Anmäl Dig",
      popupDecline: "Nej, Tack",
      popupDisclaimer: "Du anmäler dig för att få regelbundna uppdateringar via e‑post och kan när som helst avsluta prenumerationen.",
      confirmationTitle: "Tack för din anmälan!",
      confirmationText: "Du kommer nu få regelbundna uppdateringar om plattformen.",
      confirmationClose: "Stäng",
      heroTopText: "Var först med att ta del av den!",
      heroHighlightText: " Anmäl Dig Nu",
      closeButton: "✕",
      countrySE: "🇸🇪 SE",
      countryDK: "🇩🇰 DK",
      countryNO: "🇳🇴 NO",
      countryFI: "🇫🇮 FI",
      countryDE: "🇩🇪 DE",
      countryFR: "🇫🇷 FR",
      countryES: "🇪🇸 ES",
      countryIT: "🇮🇹 IT",
      countryNL: "🇳🇱 NL",
      countryBE: "🇧🇪 BE",
      aboutTitleHighlight: "Byggbranschens",
      aboutTitle: "framtid formas av oss",
      aboutSubtitle: "Construction Sourcing Sweden AB grundades ur våra egna erfarenheter av branschens bristande insyn och de återkommande problemen med tvister, sena eller uteblivna fakturabetalningar och oseriösa aktörer. Under åren med Swedish Construction Sales, där Oliver Ehrenberg var verkställande direktör och Anders Niclazon ordförande, hjälpte vi nordiska byggföretag att hitta pålitliga europeiska leverantörer och leverantörer att etablera sig i Norden. Vi såg hur fragmenterade processer, otillräcklig kommunikation och ofullständig kontaktregisterföring ledde till kostsamma förseningar, ökad misstänksamhet och i värsta fall penningtvätt. Det var denna insikt – kombinerad med vår entusiasm för teknik och förtroendebaserade samarbeten – som fick oss att i juni 2024 lansera Construction Sourcing Sweden AB, en helintegrerad plattform framtagen för att ge full transparens, förebygga tvister och bygga långsiktigt förtroende.",
      aboutVisionTitle: "Vår Vision",
      aboutVisionText: "Vår vision är att skapa den självklara mötesplatsen för alla byggföretag och leverantörer i Europa, där all kommunikation, alla kontakter och hela leverantörskedjan samlas på ett och samma ställe. Genom att centralisera projektinformation, avtal, certifikat, ekonomiska data och kontaktlistor i samma plattform gör vi det enkelt att skicka meddelanden, dela dokument och verifiera nya samarbetspartner utan onödig fördröjning. Med automatiserade aviseringar om fakturabetalningar och inbyggda due-diligence-kontroller kan användare i realtid upptäcka oseriösa aktörer och agera proaktivt – allt för att minimera risk, undvika missförstånd och säkerställa smidiga samarbeten över landsgränser.",
      featuresSummaryTitle: "Vad kan du göra på Construction Sourcing?",
      featuresSummaryIntro: "Vår plattform effektiviserar varje aspekt av byggupphandling och projekthantering. Från att hitta leverantörer till att hantera avtal, vi har dig täckt med kraftfulla verktyg och funktioner.",
      featuresProjectTitle: "Projekt & Organisation",
      featuresProject1: "Skapa och hantera flera projekt",
      featuresProject2: "Sätt milstolpar och följ upp framsteg",
      featuresProject3: "Bjud in och hantera teammedlemmar",
      featuresProject4: "Dela dokument säkert",
      featuresProject5: "Spåra projektkostnader",
      featuresProjectExpanded: "Våra projekthanteringsverktyg hjälper dig att hålla ordning och effektivitet. Från initial planering till slutleverans, håll allt på rätt spår med vår omfattande funktionsuppsättning.",
      featuresConnectTitle: "Leverantörsnätverk",
      featuresConnect1: "Hitta verifierade leverantörer och entreprenörer",
      featuresConnect2: "Jämför betyg och recensioner",
      featuresConnect3: "Begär och hantera offerter",
      featuresConnect4: "Spåra leverantörsprestanda",
      featuresConnect5: "Bygg långsiktiga relationer",
      featuresConnectExpanded: "Anslut till ett nätverk av pålitliga leverantörer och entreprenörer. Vår plattform gör det enkelt att hitta rätt partners för dina projekt och bygga varaktiga affärsrelationer.",
      featuresLegalTitle: "Juridik & Stöd",
      featuresLegal1: "Kontraktmallar och e-signering",
      featuresLegal2: "Juridisk dokumentgranskning",
      featuresLegal3: "Efterlevnadsspårning",
      featuresLegal4: "Konfliktlösning",
      featuresLegal5: "AI-drivet juridiskt stöd",
      featuresLegalExpanded: "Få expertstöd för dina byggprojekt. Från kontraktmallar till konfliktlösning, vi har dig täckt med omfattande juridiska verktyg och resurser.",
      pricingTitle: "Prisplaner som växer med dig",
      pricingIntro: "Plattformen kommer att vara helt kostnadsfri att använda. Du får direkt tillgång till kärnfunktionerna – utan att behöva betala något. I framtiden kommer det finnas möjlighet att betala för vissa tilläggstjänster och utökade funktioner för dig som vill spara ännu mer tid och pengar i bolaget.",
      pricingFreeTitle: "Kostnadsfri Tillgång",
      pricingFreePrice: "0 €/månad",
      pricingFree1: "Upp till 3 användare",
      pricingFree2: "Hantera 1 organisation",
      pricingFree3: "2 aktiva projekt",
      pricingFree4: "5 RFQ & PO arbetsflöden/månad",
      pricingFree5: "Chatthistorik 7 dagar",
      pricingFree6: "100 notifieringar/månad",
      pricingFreeCta: "Börja Gratis",
      pricingStarterTitle: "Starter",
      pricingStarterPrice: "29 €/månad",
      pricingStarter1: "Upp till 10 användare",
      pricingStarter2: "Hantera 3 organisationer",
      pricingStarter3: "5 aktiva projekt",
      pricingStarter4: "20 RFQ & PO arbetsflöden/månad",
      pricingStarter5: "Chatthistorik 30 dagar",
      pricingStarter6: "500 notifieringar/månad",
      pricingStarterCta: "Kom Igång",
      pricingPopularBadge: "Mest Populär",
      pricingAiProTitle: "AI Pro",
      pricingAiProPrice: "99 €/månad",
      pricingAiPro1: "Upp till 25 användare",
      pricingAiPro2: "Hantera 5 organisationer",
      pricingAiPro3: "10 aktiva projekt",
      pricingAiPro4: "50 RFQ & PO arbetsflöden/månad",
      pricingAiPro5: "Obegränsad chatthistorik",
      pricingAiPro6: "2000 notifieringar/månad",
      pricingAiProCta: "Uppgradera Nu",
      pricingLegalProTitle: "Legal Pro",
      pricingLegalProPrice: "149 €/månad",
      pricingLegalPro1: "Upp till 50 användare",
      pricingLegalPro2: "Hantera 10 organisationer",
      pricingLegalPro3: "25 aktiva projekt",
      pricingLegalPro4: "100 RFQ & PO arbetsflöden/månad",
      pricingLegalPro5: "Obegränsad chatthistorik",
      pricingLegalPro6: "5000 notifieringar/månad",
      pricingLegalProCta: "Uppgradera Nu",
      pricingEnterpriseTitle: "Enterprise",
      pricingEnterprisePrice: "Från 199 €/månad",
      pricingEnterprise1: "Obegränsade användare & team",
      pricingEnterprise2: "Obegränsade projekt",
      pricingEnterprise3: "Obegränsade RFQ & PO arbetsflöden",
      pricingEnterprise4: "Dedikerad kontoansvarig",
      pricingEnterprise5: "Anpassad SLA & drifttidsgaranti",
      pricingEnterprise6: "Anpassade integrationer & onboarding",
      pricingEnterpriseCta: "Kontakta Försäljning",
      pricingPrelaunchNote: "Förhandsinformation: Priser och paket är preliminära. Anmäl intresse för att få info vid lansering!",
      pricingComingSoon: "Kommer snart",
      pricingInterestCta: "Anmäl intresse",
      planBas: "Bas",
      planPlus: "Plus",
      planPremium: "Premium",
      planEnterprise: "Enterprise",
      pricingFeaturePrice: "Pris",
      pricingFeatureUsers: "Max användare",
      pricingFeatureProjects: "Max aktiva projekt",
      pricingFeatureRFQPO: "RFQ/PO processer/mån",
      pricingFeatureDocs: "Dokumenthantering & e-signering",
      pricingFeatureLegal: "Juridisk rådgivning",
      pricingFeatureAI: "AI-baserade funktioner",
      pricingFeatureChat: "Chatt & kommunikation",
      pricingFeatureNotifications: "Notifieringar",
      pricingFeatureSupport: "Supportnivå",
      pricingFeatureExtras: "Extratjänster",
      pricingBasPrice: "49 €/månad",
      pricingPlusPrice: "149 €/månad",
      pricingPremiumPrice: "499 €/månad",
      pricingEnterprisePrice: "1499 €/månad",
      pricingBasUsers: "5",
      pricingPlusUsers: "20",
      pricingPremiumUsers: "50",
      pricingEnterpriseUsers: "Obegränsat",
      pricingBasProjects: "5",
      pricingPlusProjects: "20",
      pricingPremiumProjects: "50",
      pricingEnterpriseProjects: "Obegränsat",
      pricingBasRFQPO: "20",
      pricingPlusRFQPO: "100",
      pricingPremiumRFQPO: "500",
      pricingEnterpriseRFQPO: "Obegränsat",
      pricingBasDocs: "Grundläggande (begränsad lagring), upp till 10 e-sign/mån",
      pricingPlusDocs: "Standard (mer lagring), upp till 50 e-sign/mån",
      pricingPremiumDocs: "Avancerad (stor lagring, versionshantering), upp till 200 e-sign/mån",
      pricingEnterpriseDocs: "Fullständig (obegränsad lagring & e-sign)",
      pricingBasLegal: "Självservice (mallar & guider)",
      pricingPlusLegal: "Begränsad (1 ärende/mån via e-post)",
      pricingPremiumLegal: "Utökad (5 h konsultation/mån)",
      pricingEnterpriseLegal: "Omfattande (dedikerad juristkontakt)",
      pricingBasAI: "Inga AI-funktioner",
      pricingPlusAI: "Grundläggande assistans",
      pricingPremiumAI: "Avancerade (AI-assistent & insikter)",
      pricingEnterpriseAI: "Full AI-svit (alla funktioner, anpassad)",
      pricingBasChat: "Intern chatt (inom teamet)",
      pricingPlusChat: "Team-chatt & projektkommunikation",
      pricingPremiumChat: "Avancerad chatt (gruppchatt, externa användare)",
      pricingEnterpriseChat: "Fullständig kommunikation (inkl. integrationer)",
      pricingBasNotifications: "Endast e-post",
      pricingPlusNotifications: "E-post + push-notiser",
      pricingPremiumNotifications: "E-post, push + SMS (upp till 50/mån)",
      pricingEnterpriseNotifications: "E-post, push + SMS (obegränsat)",
      pricingBasSupport: "E-post (svar inom 48 h, kontorstid)",
      pricingPlusSupport: "E-post (svar inom 24 h) + chatt",
      pricingPremiumSupport: "Prioriterad (telefon & e-post, kontorstid)",
      pricingEnterpriseSupport: "24/7 support (dedikerad kontaktperson)",
      pricingBasExtras: "Självservice (online-guider); inga extratjänster",
      pricingPlusExtras: "Onboarding via webbinarium; inga extratjänster",
      pricingPremiumExtras: "Personlig onboarding (expertstöd); SSO & API som tillval",
      pricingEnterpriseExtras: "Fullständig onboarding & utbildning; SSO & API ingår",
      basDetailsTitle: "Gratisplan (Bas) – detaljerad översikt",
      basDetailsPrice: "<strong>Pris:</strong> 0 €/månad (exkl. moms)",
      basDetailsUsers: "<strong>Användare:</strong> Upp till 3 användare",
      basDetailsOrgs: "<strong>Organisationer:</strong> Hantera 1 organisation",
      basDetailsProjects: "<strong>Projekt:</strong> Max 2 aktiva projekt samtidigt",
      basDetailsRFQPO: "<strong>RFQ & PO workflows:</strong> Max 5 st per månad",
      basDetailsDocs: "<strong>Dokumenthantering:</strong> Begränsad lagring (t.ex. max 500 MB) och upp till 10 e-signeringar per månad",
      basDetailsChat: "<strong>Chatt:</strong> Enkel team-chatt inom organisationen",
      basDetailsNotifications: "<strong>Notifieringar:</strong> 100 e-postaviseringar per månad",
      basDetailsAI: "<strong>AI-funktioner:</strong> Inga AI-funktioner aktiverade",
      basDetailsLegal: "<strong>Juridik & rådgivning:</strong> Endast tillgång till mallar och guider (ingen personlig rådgivning)",
      basDetailsSupport: "<strong>Support:</strong> Självbetjäning via FAQ och dokumentation (ingen direkt e-post- eller chatt-support)",
      basDetailsOther: "<strong>Övrigt:</strong> Branding: Plattformens logotyp och standardinställningar (ingen anpassning)",
      planFree: "Gratis",
      pricingFreeBadge: "Alltid gratis",
      pricingFreePrice: "0 €/månad",
      pricingFreeUsers: "Upp till 3 användare",
      pricingFreeProjects: "Max 2 aktiva projekt",
      pricingFreeRFQPO: "Max 5 per månad",
      pricingFreeDocs: "Begränsad lagring (max 500 MB), upp till 10 e-sign/mån",
      pricingFreeLegal: "Endast mallar & guider",
      pricingFreeAI: "Inga AI-funktioner",
      pricingFreeChat: "Endast team-chatt",
      pricingFreeNotifications: "100 e-postaviseringar/månad",
      pricingFreeSupport: "Endast självbetjäning/FAQ",
      pricingFreeExtras: "Endast plattformens branding",
      emailError: "Vänligen ange en giltig e-postadress",
      phoneError: "Vänligen ange ett giltigt telefonnummer",
      submitError: "Något gick fel. Vänligen försök igen.",
      useCase1Title: "Smart Upphandling",
      useCase1Desc: "Hitta verifierade leverantörer, hantera RFQ:er och avtal på ett och samma ställe.",
      useCase1Expanded: "Vårt upphandlingssystem förenklar hela processen från leverantörssökning till kontraktsignering. Få tillgång till ett verifierat nätverk av byggleverantörer, hantera RFQ:er och avtal effektivt.",
      useCase2Title: "Projekthantering",
      useCase2Desc: "Skapa och hantera projekt, följ upp framsteg och samarbeta med ditt team.",
      useCase2Expanded: "Effektivisera dina byggprojekt med våra omfattande hanteringsverktyg. Skapa projekt, sätt milstolpar, följ upp framsteg och samarbeta med ditt team i realtid.",
      useCase3Title: "Kommunikationsnav",
      useCase3Desc: "Chatta, dela dokument och håll dig uppdaterad med realtidsnotifieringar.",
      useCase3Expanded: "Håll ditt team uppdaterat med våra integrerade kommunikationsverktyg. Chatta i realtid, dela dokument säkert och håll dig uppdaterad med smarta notifieringar.",
      aboutFoundersTitle: "Möt Visionärerna Bakom Construction Sourcing",
      aboutOliverRole: "VD & Medgrundare",
      aboutOliverBio: "Oliver Ehrenberg är kandidatexamen i innovation management och grundare av Neo Marketing, med bred erfarenhet av CRM-implementation och datadrivna affärsmodeller. Som VD för Swedish Construction Sales 2021–2024 ledde han arbetet med att koppla nordiska byggföretag till europeiska leverantörer och bevittnade på nära håll hur bristande insyn och felaktig kommunikation orsakade onödiga konflikter. Denna insikt gjorde honom fast besluten att utveckla en plattform som inte bara hanterar data utan också möjliggör enkel, transparent dialog mellan alla parter – oavsett var i Europa de verkar.",
      aboutAndersRole: "CTO & Medgrundare",
      aboutAndersBio: "Anders Niclazon har över två decennier av erfarenhet som entreprenör och strategisk rådgivare, specialiserad på HubSpot CRM och digital försäljning. Som ordförande i Swedish Construction Sales ansvarade han för partnerskap, affärsutveckling och strukturerade due-diligence-processer som kraftigt minskade tvister och ökade förtroendet mellan kunder och leverantörer. Tillsammans med Oliver grundade han Construction Sourcing Sweden AB för att skala upp denna lösning, centralisera alla kontakter och kommunikationsflöden och skapa en trygg, effektiv plattform där varje byggföretag och leverantör i Europa kan etablera sig, växa och samarbeta framgångsrikt."
    }
  };
  
  function switchLanguage(lang) {
    localStorage.setItem('language', lang);
    applyLanguage(lang);
    
    // Dispatch language changed event
    window.dispatchEvent(new CustomEvent('languageChanged', {
      detail: { lang }
    }));
  }
  
  function applyLanguage(lang) {
    const elements = document.querySelectorAll('[data-translate]');
    elements.forEach((el) => {
      const key = el.getAttribute('data-translate');
      if (translations[lang][key]) {
        el.innerHTML = translations[lang][key];
      }
    });
  
    const heroTitle = document.querySelector('.hero h1');
    const heroSubtitle = document.querySelector('.hero .subtitle');
    const heroCTA = document.querySelector('.hero .cta-btn');
    if (heroTitle) heroTitle.innerHTML = translations[lang].heroTitle;
    if (heroSubtitle) heroSubtitle.innerHTML = translations[lang].heroSubtitle;
    if (heroCTA) heroCTA.innerHTML = translations[lang].heroCTA;
  
    const newsletterTitle = document.querySelector('.cta-section h2');
    const newsletterSub = document.querySelector('.cta-section p');
    if (newsletterTitle) newsletterTitle.innerHTML = translations[lang].newsletterHeading;
    if (newsletterSub) newsletterSub.innerHTML = translations[lang].newsletterSub;
  
    const featureHeading = document.querySelector('.features-wrapper h2');
    const featureIntro = document.querySelector('.features-wrapper .intro');
    if (featureHeading) featureHeading.innerHTML = translations[lang].featureTitle;
    if (featureIntro) featureIntro.innerHTML = translations[lang].featureIntro;
  
    document.querySelectorAll('.feature-card').forEach((card, index) => {
      const title = card.querySelector('h3');
      const desc = card.querySelector('p');
      if (title) title.innerHTML = translations[lang][`feature${index + 1}Title`];
      if (desc) desc.innerHTML = translations[lang][`feature${index + 1}Desc`];
    });
  
    const footer = {
      contact: document.querySelector('h4[data-translate="footerContact"]'),
      address: document.querySelector('h4[data-translate="footerAddress"]'),
      social: document.querySelector('h4[data-translate="footerSocial"]'),
      email: document.querySelector('p[data-translate="footerEmail"]'),
      phone: document.querySelector('p[data-translate="footerPhone"]'),
      company: document.querySelector('p[data-translate="footerCompany"]'),
      street: document.querySelector('p[data-translate="footerStreet"]'),
      city: document.querySelector('p[data-translate="footerCity"]'),
      facebook: document.querySelector('a[data-translate="footerFacebook"]'),
      instagram: document.querySelector('a[data-translate="footerInstagram"]'),
      tiktok: document.querySelector('a[data-translate="footerTiktok"]')
    };
  
    Object.entries(footer).forEach(([key, el]) => {
      if (el && translations[lang][`footer${key.charAt(0).toUpperCase() + key.slice(1)}`]) {
        el.innerHTML = translations[lang][`footer${key.charAt(0).toUpperCase() + key.slice(1)}`];
      }
    });

    // Update popup content
    const popupTitle = document.querySelector('#newsletterModal h3');
    const popupEmail = document.querySelector('#newsletterModal input[type="email"]');
    const popupPhone = document.querySelector('#newsletterModal input[type="tel"]');
    const popupSubmit = document.querySelector('#newsletterModal .submit-btn');
    const popupDecline = document.querySelector('#newsletterModal .decline-btn');
    const popupDisclaimer = document.querySelector('#newsletterModal .disclaimer');
    const confirmationTitle = document.querySelector('#confirmationPopup h3');
    const confirmationText = document.querySelector('#confirmationPopup p');
    const confirmationClose = document.querySelector('#confirmationPopup .submit-btn');

    if (popupTitle) popupTitle.innerHTML = translations[lang].popupTitle;
    if (popupEmail) popupEmail.placeholder = translations[lang].popupEmailPlaceholder;
    if (popupPhone) popupPhone.placeholder = translations[lang].popupPhonePlaceholder;
    if (popupSubmit) popupSubmit.innerHTML = translations[lang].popupSubmit;
    if (popupDecline) popupDecline.innerHTML = translations[lang].popupDecline;
    if (popupDisclaimer) popupDisclaimer.innerHTML = translations[lang].popupDisclaimer;
    if (confirmationTitle) confirmationTitle.innerHTML = translations[lang].confirmationTitle;
    if (confirmationText) confirmationText.innerHTML = translations[lang].confirmationText;
    if (confirmationClose) confirmationClose.innerHTML = translations[lang].confirmationClose;

    // Update hero top text
    const heroTopText = document.querySelector('.small-top-text');
    if (heroTopText) {
      heroTopText.innerHTML = translations[lang].heroTopText + 
        '<span class="highlight-text">' + 
        translations[lang].heroHighlightText + 
        ' <span class="arrow">➔</span></span>';
    }

    // Update close button
    const closeButton = document.querySelector('.close-btn');
    if (closeButton) {
      closeButton.innerHTML = translations[lang].closeButton;
    }

    // Update country options
    const countryOptions = document.querySelectorAll('#countrySelect option');
    countryOptions.forEach(option => {
      const countryCode = option.value.toUpperCase();
      if (translations[lang][`country${countryCode}`]) {
        option.innerHTML = translations[lang][`country${countryCode}`];
      }
    });
  }
  
  document.addEventListener('DOMContentLoaded', () => {
    const savedLang = localStorage.getItem('language') || 'sv';
    applyLanguage(savedLang);
  });